version: '3.8'
services:
  spectator_app:
    build:
      context: docker/php-apache
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
    networks:
      - spectator_app_network
  spectator_app_db:
    image: 'mysql:8.0.28'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - spectator_app_network

networks:
  spectator_app_network:
    driver: bridge