name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: docker/php-apache/Dockerfile
          failure-threshold: warning